const rows = [
  {
    heading: "Show Room Design",
    image: "https://i.ibb.co/YRgKCT0/apartment-1.png",
    price: "654646",
    action: "delete",
  },
  {
    heading: "Show Room Design",
    image: "https://i.ibb.co/YRgKCT0/apartment-1.png",
    price: "654646",
    action: "delete",
  },
  {
    heading: "Show Room Design",
    image: "https://i.ibb.co/YRgKCT0/apartment-1.png",
    price: "654646",
    action: "delete",
  },
  {
    heading: "Show Room Design",
    image: "https://i.ibb.co/YRgKCT0/apartment-1.png",
    price: "654646",
    action: "delete",
  },
  {
    heading: "Show Room Design",
    image: "https://i.ibb.co/YRgKCT0/apartment-1.png",
    price: "654646",
    action: "delete",
  },
  {
    heading: "Show Room Design",
    image: "https://i.ibb.co/YRgKCT0/apartment-1.png",
    price: "654646",
    action: "delete",
  },
  {
    heading: "Show Room Design",
    image: "https://i.ibb.co/YRgKCT0/apartment-1.png",
    price: "654646",
    action: "delete",
  },
  {
    heading: "Show Room Design",
    image: "https://i.ibb.co/YRgKCT0/apartment-1.png",
    price: "654646",
    action: "delete",
  },
  {
    heading: "Show Room Design",
    image: "https://i.ibb.co/YRgKCT0/apartment-1.png",
    price: "654646",
    action: "delete",
  },
  {
    heading: "Show Room Design",
    image: "https://i.ibb.co/YRgKCT0/apartment-1.png",
    price: "654646",
    action: "delete",
  },
  {
    heading: "Show Room Design",
    image: "https://i.ibb.co/YRgKCT0/apartment-1.png",
    price: "654646",
    action: "delete",
  },
];

const ordersData = [
  {
    name: "Selim",
    email: "selim@saikat.com",
    service: "Show Room Design",
    image: "https://i.ibb.co/YRgKCT0/apartment-1.png",
    price: "654646",
    status: "Pending",
  },
  {
    name: "Selim",
    email: "selim@saikat.com",
    service: "Show Room Design",
    image: "https://i.ibb.co/YRgKCT0/apartment-1.png",
    price: "6546456549",
    status: "Pending",
  },
  {
    name: "Selim",
    email: "selim@saikat.com",
    service: "Show Room Design",
    image: "https://i.ibb.co/YRgKCT0/apartment-1.png",
    price: "6546",
    status: "Pending",
  },
  {
    name: "Selim",
    email: "selim@saikat.com",
    service: "Show Room Design",
    image: "https://i.ibb.co/YRgKCT0/apartment-1.png",
    price: "654647",
    status: "Pending",
  },
  {
    name: "Selim",
    email: "selim@saikat.com",
    service: "Show Room Design",
    image: "https://i.ibb.co/YRgKCT0/apartment-1.png",
    price: "6546468",
    status: "Pending",
  },
  {
    name: "Selim",
    email: "selim@saikat.com",
    service: "Show Room Design",
    image: "https://i.ibb.co/YRgKCT0/apartment-1.png",
    price: "654649",
    status: "Pending",
  },
  {
    name: "Selim",
    email: "selim@saikat.com",
    service: "Show Room Design",
    image: "https://i.ibb.co/YRgKCT0/apartment-1.png",
    price: "6546410",
    status: "Pending",
  },
  {
    name: "Selim",
    email: "selim@saikat.com",
    service: "Show Room Design",
    image: "https://i.ibb.co/YRgKCT0/apartment-1.png",
    price: "65464611",
    status: "Pending",
  },
  {
    name: "Selim",
    email: "selim@saikat.com",
    service: "Show Room Design",
    image: "https://i.ibb.co/YRgKCT0/apartment-1.png",
    price: "65464612",
    status: "Pending",
  },
  {
    name: "Selim",
    email: "selim@saikat.com",
    service: "Show Room Design",
    image: "https://i.ibb.co/YRgKCT0/apartment-1.png",
    price: "65464613",
    status: "Pending",
  },
];

export { rows, ordersData };
